name: Build Android APK (debug)

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      NPM_CONFIG_CACHE: /tmp/npm-cache
      NPM_CONFIG_FUND: false
      NPM_CONFIG_AUDIT: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Clear npm cache
        run: |
          npm cache clean --force
          rm -rf ~/.npm
          mkdir -p /tmp/npm-cache

      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-linux-9477386_latest.zip
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null 2>&1
          echo "Installing Android SDK packages..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "build-tools;33.0.2" "platforms;android-33" > /dev/null

      - name: Install npm dependencies with retry
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set cache /tmp/npm-cache
          npm config set package-lock true
          npm config set fund false
          npm config set audit-level none

          # Try npm install with retries
          for i in {1..3}; do
            echo "Attempt $i: Installing npm dependencies..."
            if npm install --no-fund --no-audit --prefer-offline; then
              echo "npm install succeeded on attempt $i"
              break
            else
              echo "npm install failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "All attempts failed, trying alternative approach..."
                rm -rf node_modules package-lock.json
                npm cache clean --force
                npm install --no-package-lock --no-fund --no-audit @capacitor/cli@^6.0.0 @capacitor/core@^6.0.0 @capacitor/android@^6.0.0
                break
              fi
              sleep 10
            fi
          done

      - name: Verify Capacitor installation
        run: |
          if ! command -v npx cap &> /dev/null; then
            echo "Capacitor CLI not found, installing globally..."
            npm install -g @capacitor/cli
          fi
          npx cap --version

      - name: Prepare web directory
        run: |
          echo "Creating www directory and copying web assets..."
          mkdir -p www
          # copy top-level assets if they exist
          for f in index.html styles.css app.js data.js service-worker.js manifest.json; do
            if [ -f "$f" ]; then cp "$f" www/; fi
          done
          # copy icons
          shopt -s nullglob || true
          for icon in icon-*.png; do cp "$icon" www/ || true; done
          # if there is an app/ folder with web assets, copy them too
          if [ -d "app" ]; then
            cp -r app/* www/ || true
          fi
          echo "Web directory contents:"
          ls -la www/ || true

      - name: Update Capacitor config
        run: |
          echo "Updating capacitor.config.json to set webDir=www..."
          cat > capacitor.config.json << 'EOF'
          {
            "appId": "com.example.batsched",
            "appName": "BatSched",
            "webDir": "www",
            "bundledWebRuntime": false,
            "plugins": {
              "SplashScreen": { 
                "launchShowDuration": 0 
              }
            }
          }
          EOF
          echo "Updated config:" 
          cat capacitor.config.json

      - name: Add Android via Capacitor (if needed)
        run: |
          if [ ! -d "android" ]; then 
            echo "Adding Android platform..."
            npx cap add android
          else
            echo "Android platform already exists"
          fi

      - name: Copy and sync web assets to Android
        run: |
          echo "Copying web assets..."
          npx cap copy android || echo "Copy completed with warnings"
          echo "Syncing Android platform..."
          npx cap sync android || echo "Sync completed with warnings"

      - name: Make gradlew executable
        working-directory: android
        run: chmod +x ./gradlew

      - name: Build Android debug APK
        working-directory: android
        run: |
          echo "Building Android APK..."
          ./gradlew assembleDebug -x lint --no-daemon --stacktrace

      - name: Verify APK exists
        run: |
          if [ -f "android/app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "✅ APK built successfully"
            ls -la android/app/build/outputs/apk/debug/
          else
            echo "❌ APK not found"
            find android -name "*.apk" -type f || echo "No APK files found"
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 14

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          files: android/app/build/outputs/apk/debug/app-debug.apk
          tag_name: v${{ github.run_number }}
          name: Build ${{ github.run_number }}
          body: |
            Automated build from ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            Build date: ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
          name: batsched-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 30
