name: Build Android APK (debug)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Android SDK (action)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '9.0'

      - name: Install npm dependencies
        run: npm ci || npm install

      - name: Add Android via Capacitor (if needed)
        run: |
          npx cap --version || npm install @capacitor/cli @capacitor/core @capacitor/android --no-save
          if [ ! -d "android" ]; then npx cap add android --web-dir=.; fi

      - name: Copy and sync web assets to Android
        run: |
          npx cap copy android
          npx cap sync android || true

      - name: Build Android debug APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug -x lint --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: batsched-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
